FROM eclipse-temurin:17-jre-alpine


# Set working directory
WORKDIR /app

# Copy JAR file
COPY target/*.jar app.jar

# Expose application port
EXPOSE 5430


# Run your application
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
