
FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

COPY target/*.jar app.jar

RUN chown -R ec2-user:ec2-user /app

EXPOSE 8080

# Switch to non-root user
USER ec2-user


ENTRYPOINT [ "java", "-jar", "app.jar" ]
